### ISSUE TITLE
Custom Domain

### ISSUE THREAD

**Issue by osKlonowski** [erickzanardo/flutter-gh-pages#1]
Is there an option to add a custom domain? In order for the CNAME file to be created during build.

YML doesn't seem to accept any version of 
custom_domain: 'https://........../com/'

**Comment by erickzanardo** [comment]
I believe that you don't need to have this file configured anywhere on the action. If you create the CNAME file on the `web` folder, it will be copied to the build folder.

**Comment by osKlonowski** [comment]
Ok, I see, thank you very much

**Comment by erickzanardo** [comment]
Gonna close this, let me know if you have any more questions! Thanks!
