### ISSUE TITLE
More `flutter build web` options

### ISSUE THREAD

**Issue by hkh12** [erickzanardo/flutter-gh-pages#4]
It would be nice if we could apply any options to `flutter build web`, such as `--csp`, `--pwa-strategy` or `--dart-define`.

Is this possible?

**Comment by erickzanardo** [comment]
Probably, I am not sure how flexible the Github Actions API is to allow us pass an any number of options to the command. But I believe it could, just need to do a little research on the github documentation.

I have a lot on my plate right now and will not have this to do this research. Would you be willing to send a PR?

**Comment by erickzanardo** [comment]
Fixed on #12
