### ISSUE TITLE
Update README to include the actions/checkout should be at v2

### ISSUE THREAD

**Issue by aliasgarlabs** [erickzanardo/flutter-gh-pages#8]
This action fails with a message `fatal: could not read Username for 'https://github.com': No such device or address` when used with actions/checkout@v1 action. This is because the v1 and v2 uses different protocols to clone the repo. 

Adding this to README can help someone like me figure out why the action is failing. 

Thanks for the great action btw :)

**Comment by erickzanardo** [comment]
The readme already pointed it out to v2, I have added a comment to make it more clear.
